#!/usr/bin/env bash
# packapk.sh — assemble a minimal, API-9 APK from the cross-compiled native
# binary + a thin Java shell, WITHOUT Android Gradle Plugin (AGP dropped API 9
# support long ago). We drive the SDK build-tools directly:
#   aapt2 compile/link  -> unsigned apk with resources + manifest + native lib
#   javac + d8          -> classes.dex
#   zipalign + apksigner-> signed, installable apk
#
# Requires: $ANDROID_HOME (SDK root) with build-tools (aapt2/d8/apksigner/
# zipalign) and platforms;android-9 installed, plus a JDK (keytool).
set -euo pipefail

cd "$(dirname "$0")"

: "${ANDROID_HOME:?ANDROID_HOME must point at an Android SDK with build-tools + android-9}"
BT_VER="${BT_VER:-29.0.3}"
BT="$ANDROID_HOME/build-tools/$BT_VER"
PLAT="$ANDROID_HOME/platforms/android-9"
# javac must compile against a NEWER platform so API 30+ symbols used by the
# shell (MANAGE_EXTERNAL_STORAGE, Build.VERSION_CODES.R, etc.) resolve. The APK
# still targets minSdk 9 / targetSdk 34; runtime guards keep old devices safe.
PLAT_JAVA="${ANDROID_HOME}/platforms/android-34"
[ -d "$PLAT_JAVA" ] || PLAT_JAVA="$PLAT"

APP_ROOT=android/app/src/main
# Resolve to absolute paths up front so subshells (cd ...) never break on relative paths.
OUT="$(pwd)/android/app/build/outputs"
WORK="$(pwd)/android/app/build/apkwork"
mkdir -p "$OUT" "$WORK"

echo "[apk] using build-tools $BT_VER"

# 1) Compile the resource dir into a flat archive. aapt2 link then takes this
#    archive as a *positional* argument to ADD the resources. (Using `-R` would
#    mark it as an overlay that must override existing resources, which fails
#    with "does not override an existing resource".)
echo "[apk] aapt2 compile resources ..."
"$BT/aapt2" compile --dir "$APP_ROOT/res" -o "$WORK/res.zip"

# 2) Link: manifest + resources. (Native libs are injected via zip after link —
#    aapt2 link has no -j equivalent.) Note: do NOT pass --rename-manifest-package;
#    the manifest already declares package="com.wnacg.android", and that flag
#    combined with --min-sdk-version 9 makes newer aapt2 silently print help and
#    emit NO apk.
echo "[apk] aapt2 link ..."
echo "[apk] WORK=$WORK ; pwd=$(pwd)"
ls -la "$WORK" 2>&1 | head
"$BT/aapt2" link --no-auto-version \
    -o "$WORK/app-unsigned.apk" \
    -I "$PLAT/android.jar" \
    --manifest "$APP_ROOT/AndroidManifest.xml" \
    "$WORK/res.zip" \
    --java "$WORK/gen" \
    --min-sdk-version 9 --target-sdk-version 34 2>"$WORK/aapt2link.err"
echo "[apk] aapt2 link rc=$?"
echo "[apk] aapt2 stderr:"; cat "$WORK/aapt2link.err"
echo "[apk] app-unsigned.apk exists? $(ls -l "$WORK/app-unsigned.apk" 2>&1)"

# 2b) Inject native libraries into lib/armeabi/ (aapt2 has no -j; we zip them in).
if [ -d "$APP_ROOT/jniLibs" ]; then
    if [ ! -f "$WORK/app-unsigned.apk" ]; then
        echo "[apk] ERROR: app-unsigned.apk missing, cannot inject native libs"
        exit 1
    fi
    echo "[apk] inject native libs (lib/armeabi/libwnacg.so) ..."
    LIBPACK="$WORK/libpack"; rm -rf "$LIBPACK"; mkdir -p "$LIBPACK/lib"
    cp -r "$APP_ROOT/jniLibs"/* "$LIBPACK/lib/"
    # $WORK may be relative; resolve to absolute BEFORE cd so zip finds the output.
    APK_ABS="$(cd "$(dirname "$WORK")" && pwd)/$(basename "$WORK")/app-unsigned.apk"
    ( cd "$LIBPACK" && zip -q -r "$APK_ABS" lib )
fi

# 3) Java -> dex. R.java is generated by aapt2 (--java) into $WORK/gen.
#    Modern d8 requires --output to be a .zip/.jar or a directory, so we emit a
#    classes.zip and extract classes.dex from it.
echo "[apk] javac + d8 ..."
# NOTE: do NOT rm $WORK/gen here — aapt2 link (step 2) already generated R.java
# into it, and javac needs it. Only clean the javac output + d8 zip.
rm -rf "$WORK/obj" "$WORK/classes.zip"; mkdir -p "$WORK/obj" "$WORK/gen"
javac -source 1.8 -target 1.8 -cp "$PLAT_JAVA/android.jar" -d "$WORK/obj" \
    "$APP_ROOT/java/com/wnacg/android/MainActivity.java" \
    $(find "$WORK/gen" -name 'R.java')
"$BT/d8" --output "$WORK/classes.zip" $(find "$WORK/obj" -name '*.class')
# extract classes.dex from the d8 zip
rm -f "$WORK/classes.dex"
( cd "$WORK" && unzip -o -q classes.zip '*.dex' )
ls -l "$WORK/classes.dex" 2>/dev/null || { echo "[apk] ERROR: classes.dex not produced"; exit 1; }

# 4) Merge dex into the apk (apk is a zip).
echo "[apk] add classes.dex ..."
cp "$WORK/app-unsigned.apk" "$WORK/app-withdex.apk"
( cd "$WORK" && zip -q -j app-withdex.apk classes.dex )

# 5) Align + sign with a throwaway debug keystore.
echo "[apk] zipalign + apksigner ..."
keytool -genkeypair -v \
    -keystore "$WORK/debug.keystore" -alias androiddebugkey \
    -keyalg RSA -keysize 2048 -validity 10000 \
    -storepass android -keypass android \
    -dname "CN=wnacg,O=wnacg" 2>/dev/null
"$BT/zipalign" -p 4 "$WORK/app-withdex.apk" "$WORK/app-aligned.apk"
"$BT/apksigner" sign \
    --ks "$WORK/debug.keystore" --ks-key-alias androiddebugkey \
    --ks-pass pass:android --key-pass pass:android \
    --out "$OUT/wnacg.apk" "$WORK/app-aligned.apk"

echo "[apk] verifying ..."
"$BT/apksigner" verify "$OUT/wnacg.apk" && echo "[apk] OK: $(wc -c < "$OUT/wnacg.apk") bytes -> $OUT/wnacg.apk"
